# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1
# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  registry: "ghcr.io"
  repository: "srudyka/kbot"
  pullPolicy: IfNotPresent
  tag: "v1.1.2-b4d7cdf"
  arch: amd64
imagePullSecrets:
  - name: ghcr-login-secret
secret:
  name: "kbot"
  key: "token"
  env: "TELE_TOKEN"
securityContext:
  priviledged: true
